inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - log/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/bundle/**/*
Layout/LineLength:
  Max: 120
  Exclude:
    - Gemfile
Metrics/BlockLength:
  Exclude:
    - Guardfile
    - spec/**/*
Style/Documentation:
  Enabled: false
