inherit_from: .rubocop_todo.yml

inherit_gem:
  pundit: config/rubocop-rspec.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - log/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/bundle/**/*
Layout/LineLength:
  Max: 120
  Exclude:
    - Gemfile
Metrics/AbcSize:
  Max: 25
Metrics/BlockLength:
  Exclude:
    - config/**/*
    - Guardfile
    - spec/**/*
Metrics/MethodLength:
  Max: 15
Rails/SkipsModelValidations:
  Exclude:
    - db/seeds.rb
Style/Documentation:
  Enabled: false
