version: '3'

services:
  app:
    build:
      context: .
      args:
        APP_DIR: /bookshelf
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=p@ssw0rd
      - BUNDLE_PATH=/bundle
      - AWS_COGNITO_APP_CLIENT_ID=${AWS_COGNITO_APP_CLIENT_ID}
      - AWS_COGNITO_APP_CLIENT_SECRET=${AWS_COGNITO_APP_CLIENT_SECRET}
      - AWS_COGNITO_DOMAIN=${AWS_COGNITO_DOMAIN}
      - AWS_COGNITO_POOL_ID=${AWS_COGNITO_POOL_ID}
      - AWS_COGNITO_REGION=${AWS_COGNITO_REGION}
      - AWS_COGNITO_POOL_SITE=https://soruma-bookshelf.auth.us-east-1.amazoncognito.com/
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - ./:/bookshelf
      - ruby-bundle:/bundle

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p@ssw0rd
    ports:
      - 5432:5432
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:
  ruby-bundle:
