version: '3'

services:
  app:
    build:
      context: .
      args:
        APP_DIR: /myapp
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./:/myapp

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:
