version: '3'

services:
  app:
    build:
      context: .
      args:
        APP_DIR: /myapp
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - BUNDLE_PATH=/bundle
      - AWS_COGNITO_APP_CLIENT_ID=${AWS_COGNITO_APP_CLIENT_ID}
      - AWS_COGNITO_APP_CLIENT_SECRET=${AWS_COGNITO_APP_CLIENT_SECRET}
      - AWS_COGNITO_DOMAIN=${AWS_COGNITO_DOMAIN}
      - AWS_COGNITO_POOL_ID=${AWS_COGNITO_POOL_ID}
      - AWS_COGNITO_REGION=${AWS_COGNITO_REGION}
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - ./:/myapp
      - ruby-bundle:/bundle

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:
  ruby-bundle:
