version: '3'

services:
  app:
    build:
      context: .
      args:
        APP_DIR: /myapp
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - ./:/myapp

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:
