# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CDKs CI

on:
  push:
    paths:
      - etc/infrastructure/**
  pull_request:
    branches: [ "main" ]
    paths:
      - etc/infrastructure/**

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./etc/infrastructure/bookshelf

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: |
            etc/infrastructure/bookshelf/package-lock.json
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: etc/infrastructure/bookshelf

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: |
            etc/infrastructure/bookshelf/package-lock.json
      - run: npm ci
      - run: npm run ci-lint
