name: "Test for Lambda"
on:
  push:
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1.148.0
        with:
          bundler-cache: true
      # Add or replace database setup steps here
      # Add or replace test runners here
      - name: Run tests
        run: ruby etc/infrastructure/bookshelf/lambdas/validation-user-name/test/test_app.rb
